# Generated by Django 6.0.5 on 2026-06-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_city_customer_country_customer_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
