# Generated by Django 6.0.5 on 2026-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_languages_img_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
