# Generated by Django 6.0.5 on 2026-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_product_latitude_product_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('description1', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20)),
                ('description2', models.CharField(max_length=20)),
                ('images1', models.ImageField(upload_to='images/about/')),
                ('images2', models.ImageField(upload_to='images/about/')),
                ('images3', models.ImageField(upload_to='images/about/')),
            ],
        ),
        migrations.CreateModel(
            name='myTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='images/myTeam/')),
            ],
        ),
    ]
