# Generated by Django 6.0.5 on 2026-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_about_myteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='lang',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myteam',
            name='lang',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
    ]
