# Generated by Django 6.0.5 on 2026-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_about_lang_myteam_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer_logos/')),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('telegram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('copyright_text', models.CharField(default='© 2025 Created by Asta & Poghos | All rights reserved.', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='description1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='description2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='title1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='title2',
            field=models.CharField(max_length=100),
        ),
    ]
