# Generated by Django 6.0.5 on 2026-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_footer_alter_about_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='lang',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(default='© 2025 Created by Asta & Poghos | All rights reserved.', max_length=50),
        ),
        migrations.AlterField(
            model_name='footer',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footerLogos/'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
