# Generated by Django 6.0.5 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_footer_lang_alter_footer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(default='© 2025 Created by Asta & Poghos | All rights reserved.', max_length=100),
        ),
    ]
