# Generated by Django 6.0.5 on 2026-06-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_footer_copyright_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content_am',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title_am',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='maintitle',
            name='title_am',
        ),
        migrations.RemoveField(
            model_name='maintitle',
            name='title_en',
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='maintitle',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
    ]
