# Generated by Django 6.0.5 on 2026-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_remove_item_content_am_remove_item_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/footerLogos/'),
        ),
    ]
