# Generated by Django 6.0.5 on 2026-06-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_footer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, unique=True)),
                ('page_title', models.CharField(default='My Profile', max_length=100)),
                ('page_subtitle', models.CharField(default='Manage your account and booking settings.', max_length=200)),
                ('account_details_title', models.CharField(default='Account Details', max_length=100)),
                ('address_info_title', models.CharField(default='Address Info', max_length=100)),
                ('logout_btn', models.CharField(default='Log Out', max_length=50)),
                ('edit_btn', models.CharField(default='Edit Profile', max_length=50)),
                ('save_btn', models.CharField(default='Save Changes', max_length=50)),
                ('cancel_btn', models.CharField(default='Cancel', max_length=50)),
                ('username_label', models.CharField(default='Username', max_length=50)),
                ('email_label', models.CharField(default='Email Address', max_length=50)),
                ('first_name_label', models.CharField(default='First Name', max_length=50)),
                ('last_name_label', models.CharField(default='Last Name', max_length=50)),
                ('location_label', models.CharField(default='Location', max_length=50)),
                ('street_postal_label', models.CharField(default='Street / Postal Code', max_length=50)),
                ('verified_badge', models.CharField(default='Verified', max_length=50)),
                ('no_address_text', models.CharField(default="You haven't set up an address yet.", max_length=200)),
            ],
        ),
    ]
