# Generated by Django 6.0.5 on 2026-06-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_profiletranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10, unique=True)),
                ('login_tab', models.CharField(default='Log In', max_length=50)),
                ('signup_tab', models.CharField(default='Sign Up', max_length=50)),
                ('welcome_back_title', models.CharField(default='Welcome Back', max_length=100)),
                ('welcome_back_subtitle', models.CharField(default='Sign in to access your account', max_length=200)),
                ('create_account_title', models.CharField(default='Create an Account', max_length=100)),
                ('create_account_subtitle', models.CharField(default='Join us today to get started', max_length=200)),
                ('verify_account_title', models.CharField(default='Verify Your Account', max_length=100)),
                ('verify_account_subtitle', models.CharField(default='Enter the 6-digit code sent to you', max_length=200)),
                ('add_address_title', models.CharField(default='Add Your Address', max_length=100)),
                ('add_address_subtitle', models.CharField(default='Where should we send your bookings?', max_length=200)),
                ('email_username_label', models.CharField(default='Email or Username', max_length=100)),
                ('password_label', models.CharField(default='Password', max_length=50)),
                ('username_label', models.CharField(default='Username *', max_length=50)),
                ('email_label', models.CharField(default='Email Address *', max_length=50)),
                ('country_label', models.CharField(default='Country *', max_length=50)),
                ('city_label', models.CharField(default='City / Region *', max_length=50)),
                ('street_label', models.CharField(default='Street Address *', max_length=50)),
                ('postal_code_label', models.CharField(default='Postal Code / Zip', max_length=50)),
                ('code_label', models.CharField(default='6-Digit Code', max_length=50)),
                ('signin_btn', models.CharField(default='Sign In', max_length=50)),
                ('signup_btn', models.CharField(default='Continue to Verification', max_length=50)),
                ('verify_btn', models.CharField(default='Verify & Continue', max_length=50)),
                ('skip_btn', models.CharField(default='Skip for now', max_length=50)),
                ('save_profile_btn', models.CharField(default='Save Profile', max_length=50)),
            ],
        ),
    ]
