# Generated by Django 6.0.5 on 2026-06-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_authtranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtranslation',
            name='btn_register',
            field=models.CharField(default='Register', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_save_address',
            field=models.CharField(default='Save Address', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_saving',
            field=models.CharField(default='Saving...', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_skip_action',
            field=models.CharField(default='Skip', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_verify',
            field=models.CharField(default='Verify', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_verifying',
            field=models.CharField(default='Verifying...', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='btn_wait',
            field=models.CharField(default='Wait...', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='err_address_save_failed',
            field=models.CharField(default='Failed to save address.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='err_fill_email_or_phone',
            field=models.CharField(default='Please fill in either email or phone number.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='err_invalid_code',
            field=models.CharField(default='Invalid code. Please try again.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='err_registration_failed',
            field=models.CharField(default='Registration error. Data might already be in use.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_city_asterisk',
            field=models.CharField(default='City / Region *', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_country_asterisk',
            field=models.CharField(default='Country *', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_email',
            field=models.CharField(default='Email', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_enter_code',
            field=models.CharField(default='Enter 6-digit code', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_fill_email_or_phone',
            field=models.CharField(default='Fill in email OR phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_or',
            field=models.CharField(default='- OR -', max_length=50),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_password_asterisk',
            field=models.CharField(default='Password *', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_phone',
            field=models.CharField(default='Phone Number', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_postal_code_no_asterisk',
            field=models.CharField(default='Postal Code', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_street_asterisk',
            field=models.CharField(default='Street & Building *', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='lbl_username_asterisk',
            field=models.CharField(default='Username *', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='msg_code_sent',
            field=models.CharField(default='Code sent. Please verify.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='msg_login_success',
            field=models.CharField(default='You have successfully logged in. You can now add your address.', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='msg_profile_complete',
            field=models.CharField(default='Your profile is fully completed!', max_length=200),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='step1_title',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='step2_title',
            field=models.CharField(default='Verification', max_length=100),
        ),
        migrations.AddField(
            model_name='authtranslation',
            name='step3_title',
            field=models.CharField(default='Personal Information', max_length=100),
        ),
    ]
