# Generated by Django 6.0.5 on 2026-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.CharField(blank=True, help_text="Enter synonyms for search (e.g. 'Paris, Փարիզ, պարիս')", max_length=500, null=True),
        ),
    ]
