
import "./globals.css";
import 'swiper/css';
import 'swiper/css/effect-coverflow';
import 'swiper/css/pagination';
import Footer from "@/Components/Footer/page";
import Header from "@/Components/Header";
import { WishlistProvider } from "@/context/wishlistcontext";
import FloatingChatWidget from "@/Components/aichat/FloatingChatWidget";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body >
        <WishlistProvider>

          <main>
            <Header />
            {children}
            <Footer />

          </main>
          <FloatingChatWidget />
        </WishlistProvider>
      </body>
    </html>
  );
}
